### ISSUE TITLE
PHP Update to 8.1.30 (Security Update)

### ISSUE THREAD

**Issue by kj187** [spryker/docker-php#101]
We are using the Debian 8.1 Image (https://github.com/spryker/docker-php/blob/master/debian/bullseye/8.1/Dockerfile) 
The PHP version here is 8.1.29. Regarding some CVE fixes, please update to 8.1.30 (https://www.php.net/ChangeLog-8.php#8.1.30) and provide a new tag

Thanks :)

**Comment by kj187** [comment]
Any updates here? Its a security update which should be have some prio or? :)

**Comment by alexanderM91** [comment]
Hi @kj187, 
the image build is in progress. 

https://github.com/spryker/docker-php/pull/100/files#diff-c7f7e19faa043042ee7b0b9879f1a9a0b5f63f57255ecb57c43cd525ea67c38fR2
