### ISSUE TITLE
Composer not found

### ISSUE THREAD

**Issue by kj187** [spryker/docker-php#41]
We use the PHP 8 Buster tag 
After the merge of https://github.com/spryker/docker-php/commit/ce859148a776e1225994424701fb43a8b168d633 we have the problem that "composer" is not installed. I know, it should be installed (line 144 debian/buster/8.0/Dockerfile), but see here

![20220502161509](https://user-images.githubusercontent.com/1647861/166249129-4e6b65a9-437e-4bc2-bf77-247adc8a26ab.png)

After a second install in bash it works

![20220502161542](https://user-images.githubusercontent.com/1647861/166249237-89e95b4d-9380-40c5-8561-605e58e47e93.png)

**Comment by alexanderM91** [comment]
Hi @kj187,
an issue has been fixed and an image is ready for usage.

Thank you.

**Comment by kj187** [comment]
Thanks!
