### ISSUE TITLE
composer command not found in latest spryker/php:8.0-debian

### ISSUE THREAD

**Issue by elchenberg** [spryker/docker-php#54]
The image `docker.io/spryker/php@sha256:0da43731eeb68b10c5556c2280f4779951a1079d6a5620551523efbb44e4cb74` (arm64 version of the tag 8.0-debian) does not have composer installed.

The following command does not produce any output. The expected output would be "/usr/bin/composer":

```sh
docker run --rm docker.io/spryker/php@sha256:0da43731eeb68b10c5556c2280f4779951a1079d6a5620551523efbb44e4cb74 bash -c 'command -v composer'
```

The arm64 version of the tag 8.1-debian seems to be fine because it prints the expected output:

```sh
docker run --rm docker.io/spryker/php@sha256:f4e94299c40953f91e59c555d8084415f722f9bf5c0ed156ed29a66bf77b6fc6 bash -c 'command -v composer'
```

**Comment by alexanderM91** [comment]
Hi @elchenberg,

You can try to check with the latest digest - `sha256:45bb8ca9a6fdd7cff62ed5843c89e08a213fa4e2f4982cd10d2dc0244bc8d6d4`.

**Comment by elchenberg** [comment]
Looks good, thank you!
